apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: cd/frontend:LATEST
    generation: null
    importPolicy: {}
    name: LATEST
status:
  dockerImageRepository: ""
